// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Analytic struct {
	AnalyticsID  uuid.UUID  `json:"analytics_id"`
	LinkID       *uuid.UUID `json:"link_id"`
	SocialLinkID *uuid.UUID `json:"social_link_id"`
	UserID       uuid.UUID  `json:"user_id"`
	IpAddress    *string    `json:"ip_address"`
	UserAgent    *string    `json:"user_agent"`
	Referrer     *string    `json:"referrer"`
	ClickedAt    *time.Time `json:"clicked_at"`
}

type Auth struct {
	AuthID              uuid.UUID  `json:"auth_id"`
	UserID              uuid.UUID  `json:"user_id"`
	PasswordHash        string     `json:"password_hash"`
	Salt                string     `json:"salt"`
	IsEmailVerified     *bool      `json:"is_email_verified"`
	VerificationToken   *string    `json:"verification_token"`
	ResetToken          *string    `json:"reset_token"`
	ResetTokenExpiresAt *time.Time `json:"reset_token_expires_at"`
	LastLogin           *time.Time `json:"last_login"`
}

type Link struct {
	LinkID             uuid.UUID  `json:"link_id"`
	UserID             uuid.UUID  `json:"user_id"`
	Title              string     `json:"title"`
	Url                string     `json:"url"`
	Description        *string    `json:"description"`
	Icon               *string    `json:"icon"`
	CustomThumbnailUrl *string    `json:"custom_thumbnail_url"`
	Position           int32      `json:"position"`
	IsActive           *bool      `json:"is_active"`
	ClickCount         *int32     `json:"click_count"`
	CreatedAt          *time.Time `json:"created_at"`
	UpdatedAt          *time.Time `json:"updated_at"`
}

type Section struct {
	SectionID   uuid.UUID  `json:"section_id"`
	UserID      uuid.UUID  `json:"user_id"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Position    int32      `json:"position"`
	IsActive    *bool      `json:"is_active"`
	CreatedAt   *time.Time `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
}

type SectionLink struct {
	SectionLinkID uuid.UUID `json:"section_link_id"`
	SectionID     uuid.UUID `json:"section_id"`
	LinkID        uuid.UUID `json:"link_id"`
	Position      int32     `json:"position"`
}

type SocialLink struct {
	SocialLinkID uuid.UUID  `json:"social_link_id"`
	UserID       uuid.UUID  `json:"user_id"`
	Platform     string     `json:"platform"`
	Username     string     `json:"username"`
	Url          string     `json:"url"`
	Position     int32      `json:"position"`
	IsActive     *bool      `json:"is_active"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
}

type Theme struct {
	ThemeID         uuid.UUID  `json:"theme_id"`
	Name            string     `json:"name"`
	BackgroundColor *string    `json:"background_color"`
	TextColor       *string    `json:"text_color"`
	ButtonStyle     *string    `json:"button_style"`
	FontFamily      *string    `json:"font_family"`
	IsPremium       *bool      `json:"is_premium"`
	IsActive        *bool      `json:"is_active"`
	CreatedAt       *time.Time `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

type User struct {
	UserID          uuid.UUID  `json:"user_id"`
	Username        string     `json:"username"`
	Email           string     `json:"email"`
	FirstName       *string    `json:"first_name"`
	LastName        *string    `json:"last_name"`
	ProfileImageUrl *string    `json:"profile_image_url"`
	Bio             *string    `json:"bio"`
	Theme           *string    `json:"theme"`
	CustomDomain    *string    `json:"custom_domain"`
	IsPremium       *bool      `json:"is_premium"`
	CreatedAt       *time.Time `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

type UserTheme struct {
	UserThemeID        uuid.UUID  `json:"user_theme_id"`
	UserID             uuid.UUID  `json:"user_id"`
	Name               string     `json:"name"`
	BackgroundColor    *string    `json:"background_color"`
	BackgroundImageUrl *string    `json:"background_image_url"`
	TextColor          *string    `json:"text_color"`
	ButtonStyle        *string    `json:"button_style"`
	FontFamily         *string    `json:"font_family"`
	CustomCss          *string    `json:"custom_css"`
	IsActive           *bool      `json:"is_active"`
	CreatedAt          *time.Time `json:"created_at"`
	UpdatedAt          *time.Time `json:"updated_at"`
}
