// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Analytic struct {
	AnalyticsID uuid.UUID  `json:"analytics_id"`
	ItemID      uuid.UUID  `json:"item_id"`
	UserID      uuid.UUID  `json:"user_id"`
	IpAddress   *string    `json:"ip_address"`
	UserAgent   *string    `json:"user_agent"`
	Referrer    *string    `json:"referrer"`
	ClickedAt   *time.Time `json:"clicked_at"`
}

type Auth struct {
	AuthID              uuid.UUID  `json:"auth_id"`
	UserID              uuid.UUID  `json:"user_id"`
	PasswordHash        string     `json:"password_hash"`
	Salt                string     `json:"salt"`
	IsEmailVerified     *bool      `json:"is_email_verified"`
	VerificationToken   *string    `json:"verification_token"`
	ResetToken          *string    `json:"reset_token"`
	ResetTokenExpiresAt *time.Time `json:"reset_token_expires_at"`
	LastLogin           *time.Time `json:"last_login"`
}

type ContentItem struct {
	ItemID       uuid.UUID    `json:"item_id"`
	UserID       uuid.UUID    `json:"user_id"`
	ContentID    string       `json:"content_id"`
	ContentType  string       `json:"content_type"`
	Title        *string      `json:"title"`
	Href         *string      `json:"href"`
	Url          *string      `json:"url"`
	MediaType    *string      `json:"media_type"`
	DesktopX     *int32       `json:"desktop_x"`
	DesktopY     *int32       `json:"desktop_y"`
	DesktopStyle *string      `json:"desktop_style"`
	MobileX      *int32       `json:"mobile_x"`
	MobileY      *int32       `json:"mobile_y"`
	MobileStyle  *string      `json:"mobile_style"`
	Halign       *string      `json:"halign"`
	Valign       *string      `json:"valign"`
	ContentData  pgtype.JSONB `json:"content_data"`
	Overrides    pgtype.JSONB `json:"overrides"`
	IsActive     *bool        `json:"is_active"`
	CreatedAt    *time.Time   `json:"created_at"`
	UpdatedAt    *time.Time   `json:"updated_at"`
}

type OauthAccount struct {
	OauthID        uuid.UUID  `json:"oauth_id"`
	UserID         uuid.UUID  `json:"user_id"`
	Provider       string     `json:"provider"`
	ProviderUserID string     `json:"provider_user_id"`
	Email          *string    `json:"email"`
	Name           *string    `json:"name"`
	AccessToken    *string    `json:"access_token"`
	RefreshToken   *string    `json:"refresh_token"`
	TokenExpiresAt *time.Time `json:"token_expires_at"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
}

type Theme struct {
	ThemeID         uuid.UUID  `json:"theme_id"`
	Name            string     `json:"name"`
	BackgroundColor *string    `json:"background_color"`
	TextColor       *string    `json:"text_color"`
	ButtonStyle     *string    `json:"button_style"`
	FontFamily      *string    `json:"font_family"`
	IsPremium       *bool      `json:"is_premium"`
	IsActive        *bool      `json:"is_active"`
	CreatedAt       *time.Time `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

type User struct {
	UserID          uuid.UUID  `json:"user_id"`
	Username        string     `json:"username"`
	Handle          string     `json:"handle"`
	Email           string     `json:"email"`
	FirstName       *string    `json:"first_name"`
	LastName        *string    `json:"last_name"`
	Bio             *string    `json:"bio"`
	ProfileImageUrl *string    `json:"profile_image_url"`
	LayoutVersion   *string    `json:"layout_version"`
	CustomDomain    *string    `json:"custom_domain"`
	IsPremium       *bool      `json:"is_premium"`
	IsAdmin         *bool      `json:"is_admin"`
	Onboarded       *bool      `json:"onboarded"`
	CreatedAt       *time.Time `json:"created_at"`
	UpdatedAt       *time.Time `json:"updated_at"`
}

type UserTheme struct {
	UserThemeID        uuid.UUID  `json:"user_theme_id"`
	UserID             uuid.UUID  `json:"user_id"`
	Name               string     `json:"name"`
	BackgroundColor    *string    `json:"background_color"`
	BackgroundImageUrl *string    `json:"background_image_url"`
	TextColor          *string    `json:"text_color"`
	ButtonStyle        *string    `json:"button_style"`
	FontFamily         *string    `json:"font_family"`
	CustomCss          *string    `json:"custom_css"`
	IsActive           *bool      `json:"is_active"`
	CreatedAt          *time.Time `json:"created_at"`
	UpdatedAt          *time.Time `json:"updated_at"`
}
