// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username,
  email,
  first_name,
  last_name
) VALUES (
  $1, $2, $3, $4
)
RETURNING user_id, username, email, first_name, last_name, profile_image_url, bio, theme, custom_domain, is_premium, created_at, updated_at
`

type CreateUserParams struct {
	Username  string  `json:"username"`
	Email     string  `json:"email"`
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ProfileImageUrl,
		&i.Bio,
		&i.Theme,
		&i.CustomDomain,
		&i.IsPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, email, first_name, last_name, profile_image_url, bio, theme, custom_domain, is_premium, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ProfileImageUrl,
		&i.Bio,
		&i.Theme,
		&i.CustomDomain,
		&i.IsPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, first_name, last_name, profile_image_url, bio, theme, custom_domain, is_premium, created_at, updated_at FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ProfileImageUrl,
		&i.Bio,
		&i.Theme,
		&i.CustomDomain,
		&i.IsPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, email, first_name, last_name, profile_image_url, bio, theme, custom_domain, is_premium, created_at, updated_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ProfileImageUrl,
		&i.Bio,
		&i.Theme,
		&i.CustomDomain,
		&i.IsPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, username, email, first_name, last_name, profile_image_url, bio, theme, custom_domain, is_premium, created_at, updated_at FROM users
ORDER BY created_at
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.ProfileImageUrl,
			&i.Bio,
			&i.Theme,
			&i.CustomDomain,
			&i.IsPremium,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
  username = COALESCE($2, username),
  email = COALESCE($3, email),
  first_name = COALESCE($4, first_name),
  last_name = COALESCE($5, last_name),
  profile_image_url = COALESCE($6, profile_image_url),
  bio = COALESCE($7, bio),
  updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
RETURNING user_id, username, email, first_name, last_name, profile_image_url, bio, theme, custom_domain, is_premium, created_at, updated_at
`

type UpdateUserParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Username        string    `json:"username"`
	Email           string    `json:"email"`
	FirstName       *string   `json:"first_name"`
	LastName        *string   `json:"last_name"`
	ProfileImageUrl *string   `json:"profile_image_url"`
	Bio             *string   `json:"bio"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.ProfileImageUrl,
		arg.Bio,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.ProfileImageUrl,
		&i.Bio,
		&i.Theme,
		&i.CustomDomain,
		&i.IsPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
